import React from "react"
import stateMachine from "./state-machine"

export const wrapRootElement = stateMachine

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      key="NunitoSans-LightItalic-1"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-300italic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-LightItalic-2"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-300italic.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-Light-1"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-regular.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-Light-2"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-regular.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-Regular-1"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-regular.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-Regular-2"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-regular.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-Italic-1"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-italic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-Italic-2"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-italic.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-SemiBold-1"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-600.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-SemiBold-2"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-600.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-SemiBoldItalic-1"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-600italic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-SemiBoldItalic-2"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-600italic.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-Bold-1"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-700.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="NunitoSans-Bold-2"
      rel="preload"
      href="/fonts/nunito-v16-latin_cyrillic-700.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
    />,
    <link
      key="Kalam-Regular-1"
      rel="preload"
      href="/fonts/kalam-latin-regular.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="Kalam-Regular-2"
      rel="preload"
      href="/fonts/kalam-latin-regular.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
    />,
    <link
      key="Kalam-Bold-1"
      rel="preload"
      href="/fonts/kalam-latin-700.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="Kalam-Bold-2"
      rel="preload"
      href="/fonts/kalam-latin-700.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
    />,
  ])
}
